/*
 * This class was automatically generated by NetBeans. 
 * Note the ApplicationPath annotation here, which 
 * becomes part of the URI for accessing the REST services.
 */
package rest;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author tm352
 */
@javax.ws.rs.ApplicationPath("webresources")
public class ApplicationConfig extends Application
{

   @Override
   public Set<Class<?>> getClasses()
   {
      Set<Class<?>> resources = new java.util.HashSet<>();
      addRestResourceClasses(resources);
      return resources;
   }

   /**
    * Do not modify addRestResourceClasses() method.
    * It is automatically populated with
    * all resources defined in the project.
    * If required, comment out calling this method in getClasses().
    */
   private void addRestResourceClasses(Set<Class<?>> resources)
   {
      resources.add(rest.CaseResource.class);
   }
   
}
